import React from 'react'
import styles from './tips.module.css'
import '../x.svg'
import '../y.svg'
import '../z.svg'

const tips = [
    { icon: "x.svg", name: "Search", content: `Simply add a keyword or a term related to your business in the slogan maker search box. Wait for the magic to happen.` },
    { icon: "y.svg", name: "Select", content: `Choose from thousands of options generated by the slogan maker that fit your needs.` },
    { icon: "z.svg", name: "Stand out", content: `Congrats on your new slogan. It's time to win the world!` }
]

export default function Tips() {
    return (
        <div className={styles.tips}>
            <div className={styles.tipsitems}>
                {tips.map((tip) => (
                    <div className={styles.tipitemlist}>
                            <img className={styles.img} src={tip.icon} alt="" />
                            <p className={styles.titlename}>{tip.name}</p>
                            <p className={styles.tipdesc}>{tip.content}</p>
                    </div>
                ))}
            </div>
        </div>
    )
}
